import type { NextPage } from "next";
import Head from "next/head";
import { getDistance } from "geolib";
import { Header, DialogC } from "../src/components";
import { Button, Container } from "@mui/material";
import { GrAdd } from "react-icons/gr";
import React from "react";

const Home: NextPage = () => {
  const [open, setOpen] = React.useState(false);

  const handleClickOpen = () => {
    setOpen(true);
  };
  const handleClose = () => {
    setOpen(false);
  };
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {/* {getDistance(
        { latitude: 33.98203286444763, longitude: -6.867345572938709 }, // HCP Club
        // 34.004339764338056, -6.856543549272664
        { latitude: 34.004339764338056, longitude: -6.856543549272664 }
      )} */}
      <DialogC title="Choose Drone to Send" onClose={handleClose} open={open} />
      <Container
        style={{
          marginTop: "20px",
        }}
        maxWidth="lg"
      >
        <Button
          onClick={handleClickOpen}
          variant="contained"
          size="large"
          startIcon={<GrAdd color="#fff" />}
          style={{
            borderRadius: "50px",
            backgroundColor: "#1976d2",
            color: "#fff",
          }}
        >
          Send A Drone
        </Button>
      </Container>
    </div>
  );
};

export default Home;
